name: deploy-app

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: https://github.com/SebastianWcislik/Intranet/tree/main/IntranetAPP
          file: https://github.com/SebastianWcislik/Intranet/tree/main/IntranetAPP/Dockerfile
          push: true
          tags: sebastianwcislik/intranetapp:dev
