name: Docker-build-and-push-APP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file IntranetAPP/Dockerfile --tag sebastianwcislik/intranetapp:APP

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Build
      run: docker build -f IntranetAPP/Dockerfile --build-arg BASE=nanoserver-ltsc2022 -t sebastianwcislik/intranetapp:APP .
      
    - name: Docker Push
      run: docker push sebastianwcislik/intranetapp:APP
