name: Docker-build-and-push-API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file IntranetAPI/Dockerfile --tag sebastianwcislik/intranetapp:API

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Build
      run: docker build -f IntranetAPI/Dockerfile --build-arg BASE=nanoserver-ltsc2022 -t sebastianwcislik/intranetapp:API .
      
    - name: Docker Push
      run: docker push sebastianwcislik/intranetapp:API

    #runs-on: ubuntu-latest

    #steps:
    #- uses: actions/checkout@v3
    #- name: Build the Docker image
    #  run: docker build . --file IntranetAPI/Dockerfile --tag sebastianwcislik/intranetapp:API

    #- name: Docker Login
    #  uses: docker/login-action@v2.1.0
    #  with:
    #    username: ${{ secrets.DOCKERHUB_USERNAME }}
    #    password: ${{ secrets.DOCKERHUB_TOKEN }}

    #- name: Set up QEMU
    #  uses: docker/setup-qemu-action@v2
      
    #- name: Set up Docker Buildx
    #  uses: docker/setup-buildx-action@v2

    #- name: Build and push
    #  uses: docker/build-push-action@v3
    #  with:
    #    context: .
    #    file: IntranetAPI/Dockerfile
    #    push: true
    #    tags: sebastianwcislik/intranetapp:API
